---

# Server installation
- hosts: my_sensu_server
  roles:
    - rabbitmq
    - redis
    - uchiwa
    - role: sensu
      sensu_install_server: true
      sensu_install_api: true

# Client installation
- hosts: my_client1
  vars:
    server__sensu: my_sensu_server
  roles:
    - role: sensu
      vars:
        sensu_api_host: "{{ server__sensu }}"
        sensu_rabbitmq_host: "{{ server__sensu }}"
        sensu_redis_host: "{{ server__sensu }}"
